id: IE33C13DB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:23:00+00:00'
last_modified: '2022-06-16T05:31:58.518591+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4474
  title: རྒྱལ་བ་ཚངས་དབྱངས་རྒྱ་མཚོའི་མགུར་གླུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    394F:
      image_group_id: I1KG4504
      title: ''
      total_pages: 22
      order: 1
      base_file: 394F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
